// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/taufiksoleh/backend-mp/internal/domain/repository (interfaces: PropertyRepository)
//
// Generated by this command:
//
//	mockgen -destination=internal/domain/repository/mock/mock_property_repository.go -package=mockrepo github.com/taufiksoleh/backend-mp/internal/domain/repository PropertyRepository
//

// Package mockrepo is a generated GoMock package.
package mockrepo

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/taufiksoleh/backend-mp/internal/domain/entity"
	repository "github.com/taufiksoleh/backend-mp/internal/domain/repository"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockPropertyRepository is a mock of PropertyRepository interface.
type MockPropertyRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPropertyRepositoryMockRecorder
	isgomock struct{}
}

// MockPropertyRepositoryMockRecorder is the mock recorder for MockPropertyRepository.
type MockPropertyRepositoryMockRecorder struct {
	mock *MockPropertyRepository
}

// NewMockPropertyRepository creates a new mock instance.
func NewMockPropertyRepository(ctrl *gomock.Controller) *MockPropertyRepository {
	mock := &MockPropertyRepository{ctrl: ctrl}
	mock.recorder = &MockPropertyRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPropertyRepository) EXPECT() *MockPropertyRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPropertyRepository) Create(ctx context.Context, property *entity.Property) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, property)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPropertyRepositoryMockRecorder) Create(ctx, property any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPropertyRepository)(nil).Create), ctx, property)
}

// Delete mocks base method.
func (m *MockPropertyRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPropertyRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPropertyRepository)(nil).Delete), ctx, id)
}

// FindAllWithFilter mocks base method.
func (m *MockPropertyRepository) FindAllWithFilter(ctx context.Context, filter repository.PropertyFilter) (repository.PaginatedProperties, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllWithFilter", ctx, filter)
	ret0, _ := ret[0].(repository.PaginatedProperties)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllWithFilter indicates an expected call of FindAllWithFilter.
func (mr *MockPropertyRepositoryMockRecorder) FindAllWithFilter(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllWithFilter", reflect.TypeOf((*MockPropertyRepository)(nil).FindAllWithFilter), ctx, filter)
}

// FindByDocumentID mocks base method.
func (m *MockPropertyRepository) FindByDocumentID(ctx context.Context, documentID string) (*entity.Property, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByDocumentID", ctx, documentID)
	ret0, _ := ret[0].(*entity.Property)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByDocumentID indicates an expected call of FindByDocumentID.
func (mr *MockPropertyRepositoryMockRecorder) FindByDocumentID(ctx, documentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByDocumentID", reflect.TypeOf((*MockPropertyRepository)(nil).FindByDocumentID), ctx, documentID)
}

// FindByID mocks base method.
func (m *MockPropertyRepository) FindByID(ctx context.Context, id uuid.UUID) (*entity.Property, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*entity.Property)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockPropertyRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockPropertyRepository)(nil).FindByID), ctx, id)
}

// FindOrCreateFacility mocks base method.
func (m *MockPropertyRepository) FindOrCreateFacility(ctx context.Context, name string) (*entity.Facility, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOrCreateFacility", ctx, name)
	ret0, _ := ret[0].(*entity.Facility)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOrCreateFacility indicates an expected call of FindOrCreateFacility.
func (mr *MockPropertyRepositoryMockRecorder) FindOrCreateFacility(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOrCreateFacility", reflect.TypeOf((*MockPropertyRepository)(nil).FindOrCreateFacility), ctx, name)
}

// Update mocks base method.
func (m *MockPropertyRepository) Update(ctx context.Context, property *entity.Property) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, property)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPropertyRepositoryMockRecorder) Update(ctx, property any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPropertyRepository)(nil).Update), ctx, property)
}

// WithTx mocks base method.
func (m *MockPropertyRepository) WithTx(tx *gorm.DB) repository.PropertyRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", tx)
	ret0, _ := ret[0].(repository.PropertyRepository)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockPropertyRepositoryMockRecorder) WithTx(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockPropertyRepository)(nil).WithTx), tx)
}
