// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/taufiksoleh/backend-mp/internal/usecase (interfaces: PropertyUsecase)
//
// Generated by this command:
//
//	mockgen -destination=internal/usecase/mock/mock_property_usecase.go -package=mockusecase github.com/taufiksoleh/backend-mp/internal/usecase PropertyUsecase
//

// Package mockusecase is a generated GoMock package.
package mockusecase

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	entity "github.com/taufiksoleh/backend-mp/internal/domain/entity"
	repository "github.com/taufiksoleh/backend-mp/internal/domain/repository"
	usecase "github.com/taufiksoleh/backend-mp/internal/usecase"
	gomock "go.uber.org/mock/gomock"
)

// MockPropertyUsecase is a mock of PropertyUsecase interface.
type MockPropertyUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockPropertyUsecaseMockRecorder
	isgomock struct{}
}

// MockPropertyUsecaseMockRecorder is the mock recorder for MockPropertyUsecase.
type MockPropertyUsecaseMockRecorder struct {
	mock *MockPropertyUsecase
}

// NewMockPropertyUsecase creates a new mock instance.
func NewMockPropertyUsecase(ctrl *gomock.Controller) *MockPropertyUsecase {
	mock := &MockPropertyUsecase{ctrl: ctrl}
	mock.recorder = &MockPropertyUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPropertyUsecase) EXPECT() *MockPropertyUsecaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPropertyUsecase) Create(ctx context.Context, req usecase.PropertyRequest) (*entity.Property, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(*entity.Property)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPropertyUsecaseMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPropertyUsecase)(nil).Create), ctx, req)
}

// Delete mocks base method.
func (m *MockPropertyUsecase) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPropertyUsecaseMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPropertyUsecase)(nil).Delete), ctx, id)
}

// GetAll mocks base method.
func (m *MockPropertyUsecase) GetAll(ctx context.Context, filter repository.PropertyFilter) (repository.PaginatedProperties, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, filter)
	ret0, _ := ret[0].(repository.PaginatedProperties)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockPropertyUsecaseMockRecorder) GetAll(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockPropertyUsecase)(nil).GetAll), ctx, filter)
}

// GetByDocumentID mocks base method.
func (m *MockPropertyUsecase) GetByDocumentID(ctx context.Context, documentID string) (*entity.Property, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByDocumentID", ctx, documentID)
	ret0, _ := ret[0].(*entity.Property)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByDocumentID indicates an expected call of GetByDocumentID.
func (mr *MockPropertyUsecaseMockRecorder) GetByDocumentID(ctx, documentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByDocumentID", reflect.TypeOf((*MockPropertyUsecase)(nil).GetByDocumentID), ctx, documentID)
}

// GetByID mocks base method.
func (m *MockPropertyUsecase) GetByID(ctx context.Context, id uuid.UUID) (*entity.Property, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.Property)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPropertyUsecaseMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPropertyUsecase)(nil).GetByID), ctx, id)
}

// Update mocks base method.
func (m *MockPropertyUsecase) Update(ctx context.Context, id uuid.UUID, req usecase.PropertyRequest) (*entity.Property, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, req)
	ret0, _ := ret[0].(*entity.Property)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockPropertyUsecaseMockRecorder) Update(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPropertyUsecase)(nil).Update), ctx, id, req)
}
